branches:
  except:
    - document/*
    - doc/*

skip_tags: true

image: Visual Studio 2015

platform: Any CPU

configuration: Release

before_build:
    - nuget restore Kinugasa.sln

build: 
  parallel: true
  project: Kinugasa.sln
  verbosity: normal

after_test:
    - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/noisolation /testcontainer:""Mvvm.Test.dll" -targetdir:".\Test\Kinugasa.Mvvm.Test\bin\Release" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:Kinugasa_coverage.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "Kinugasa_coverage.xml"