branches:
  only:
    - master
    - develop/*

skip_tags: true
skip_commits: *\.(png|jpg|jpeg|bmp|gif|md)/

image: Visual Studio 2015

platform: Any CPU

configuration: Release

build: 
  parallel: true  
