branches:
  except:
    - document/*
    - doc/*

skip_tags: true

image: Visual Studio 2015

platform: Any CPU

configuration: Release

build: 
  parallel: true
  project: Kinugasa.sln
  verbosity: minimal
